name: Deploy Evidence Staging

on:
  pull_request:
    branches:
      - main
    paths:
      - evidence/**

env:
  EVIDENCE_SOURCE__mathews_recurring_revenue__location: US
  EVIDENCE_SOURCE__mathews_recurring_revenue__authenticator: gcloud-cli
  EVIDENCE_SOURCE__mathews_recurring_revenue__project_id: mathews-recurring-revenue-stg
  EVIDENCE_VAR__access_policy: pub

jobs:
  evidence-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      id-token: write

    defaults:
      run:
        working-directory: evidence

    steps:
      - name: Clone Repository
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v3
        with:
          project_id: mathews-recurring-revenue-stg
          workload_identity_provider: projects/724228842720/locations/global/workloadIdentityPools/github/providers/mathews-recurring-revenue
          service_account: github@mathews-recurring-revenue-stg.iam.gserviceaccount.com

      - name: Install dependencies
        run: npm ci

      - name: Fetch Data
        run: npm run sources:strict

      - name: Build Application
        run: npm run build:strict

      - name: Copy Build to Vercel Directory
        run: |
          mkdir -p .vercel/output/static
          cp -r build/* .vercel/output/static

      - name: Create Vercel Deploy Config
        run: |
          cat << EOF > .vercel/project.json
          {
            "orgId": "$VERCEL_ORG_ID",
            "projectId": "$VERCEL_PROJECT_ID",
            "projectName": "mathews-recurring-revenue-stg"
          }
          EOF

          # cat > .vercel/output/config.json << EOF
          # {
          #   "version": 3,
          #   "routes": [
          #     { "handle": "filesystem" },
          #     { "src": "/(.*)", "dest": "/index.html" }
          #   ]
          # }
          # EOF

      - name: Debug
        run: |
          ls -lA .vercel/
          cat .vercel/project.json

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --token=${{ secrets.VERCEL_TOKEN }} --yes --environment=production

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --prod --prebuilt

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      # - name: Build Project Artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --prod --output=build