name: Terraform Deploy Production

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/mathews-recurring-revenue-prd/**'
jobs:
  deploy-terraform-prd:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      tf-project: terraform/mathews-recurring-revenue-prd
